### PR TITLE
Add key delete

### LINKED ISSUE #45: Update key/delete.sh
https://github.com/EasyGnuPG/pgpg/blob/d108baf68dc2eb6de3d360b4bb1e06f2017d0946/src/cmd/key/delete.sh#L23

### PR DESCRIPTION
**Pull request by diveshuttam**
closes #45

### CODE REVIEW

**Comment by diveshuttam** [comment]
Hi @dashohoxha, Currently egpg doesn't ask for confirmation before key deletion. Is this intended behavior? I have emulated the same for now in this script but probably we should confirm it from the user.

**Comment by dashohoxha** [comment]
Interesting question. I don't remember thinking about this before. Maybe a confirmation is not needed because this command is not something that can be done by mistake (`egpg key delete`).

If we have to add a confirmation it can be done on the bash script (the python script will not be changed). It can be something like this: `Are you sure you want to delete the key? [y/N] `

In this case we may need to fix the testing scripts as well. So, for the time being let's keep the behavior unchanged, and you can add this suggestion in a list of possible improvements that we can discuss later.

**Review by dashohoxha — APPROVED** [review]
This seems Ok to me, you can merge it.

**Comment by diveshuttam** [comment]
I am merging this for now and have opened the relevant issues. Will address this in another PR.

**Pull request merged**
