### PR TITLE
key gen added

### LINKED ISSUE #46: Update key/gen.sh
https://github.com/EasyGnuPG/pgpg/blob/d108baf68dc2eb6de3d360b4bb1e06f2017d0946/src/cmd/key/gen.sh#L62

### PR DESCRIPTION
**Pull request by diveshuttam**
closes #46 

refererence:
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=lang/python/examples/genkey.py;h=a043500eded29673fcf34b486637a3336f452a61;hb=d8beab30c44482fb7a3e445b92cec482792b2ca0

@dashohoxha most of the tests are passing, I am still not able to run t27 and t28 on my container. Please test them on yours once.

### CODE REVIEW

**Comment by dashohoxha** [comment]
For me t03 does not work on pgpg (it works on egpg).

> I am still not able to run t27 and t28 on my container

They still work for me. Try 
```
ps ax | grep haveged
service haveged status
service haveged start
```

**Comment by diveshuttam** [comment]
haveged status is giving the following log and and haveged start is not working.
```
 haveged.service - Entropy daemon using the HAVEGE algorithm
   Loaded: loaded (/lib/systemd/system/haveged.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-06-26 18:24:12 UTC; 2s ago
     Docs: man:haveged(8)
           http://www.issihosts.com/haveged/
  Process: 27596 ExecStart=/usr/sbin/haveged --Foreground --verbose=1 $DAEMON_ARGS (code=exited, status=127)
 Main PID: 27596 (code=exited, status=127)

Jun 26 18:24:12 pgpg-bionic systemd[1]: Started Entropy daemon using the HAVEGE algorithm.
Jun 26 18:24:12 pgpg-bionic systemd[27596]: Failed to configure loopback device: Operation not permitted
Jun 26 18:24:12 pgpg-bionic haveged[27596]: /usr/sbin/haveged: error while loading shared libraries: libhavege.so.1: ca
Jun 26 18:24:12 pgpg-bionic systemd[1]: haveged.service: Main process exited, code=exited, status=127/n/a
Jun 26 18:24:12 pgpg-bionic systemd[1]: haveged.service: Failed with result 'exit-code'.
```
@dashohoxha can you add the debug log for t03 here, it is passing on bionic on my machine.
I have made sure that I am on the right branch.

```bash
pgpg-bionic root@pgpg-bionic:/host/pgpg/tests
==> # ./run.sh t03-init.t

=> ./t03-init.t
ok 1 - egpg
ok 2 - egpg init
ok 3 - egpg key fetch
ok 4 - egpg init dir1 (keep old dir)
ok 5 - egpg init dir2 (keep old dir)
ok 6 - egpg init dir1 (remove old dir)
ok 7 - egpg init (remove old dir)
# passed all 7 test(s)
1..7
```

**Comment by dashohoxha** [comment]
About t03, on the same container, it works on egpg but does not work on pgpg.
This is the diff between them:
```
Only in egpg/tests/gnupg: S.gpg-agent
Only in egpg/tests/gnupg: S.gpg-agent.browser
Only in egpg/tests/gnupg: S.gpg-agent.extra
Only in egpg/tests/gnupg: S.gpg-agent.ssh
Binary files egpg/tests/gnupg/pubring.kbx and pgpg/tests/gnupg/pubring.kbx diffee
r
Only in egpg/tests/gnupg: pubring.kbx~
Only in egpg/tests/gnupg: tofu.db
Only in egpg/tests/gnupg: trustdb.gpg
```

What is the diff between them in your container?

**Comment by dashohoxha** [comment]
About haveged, the key message may be this: 'Failed to configure loopback device: Operation not permitted'. You can google for it.

Why it works for me but not for you? I am running docker as root, maybe you are not. Maybe you have a different version of docker. Maybe you have a different version of systemd, a different version of kernel, etc. Maybe you are running AppArmor and it affects the work of docker. I don't know.

First of all make sure that you don't have problems with the disk space, and also try a reboot (sometimes it solves the problem for me, since I keep it sleep-and-wake for months).

**Comment by diveshuttam** [comment]
>About t03, on the same container, it works on egpg but does not work on pgpg.
This is the diff between them:

Sorry but I didn't get when is the diff taken and what exactly its between. 
I have tried the following and the gnupg folders are exact same. This is before running the tests.

```
==> # diff -qr /host/egpg/tests /host/pgpg/tests/
Files /host/egpg/tests/t10-verify.t and /host/pgpg/tests/t10-verify.t differ
Files /host/egpg/tests/t12-open.t and /host/pgpg/tests/t12-open.t differ
Files /host/egpg/tests/t24-key-pass.t and /host/pgpg/tests/t24-key-pass.t differ
Files /host/egpg/tests/t34-split-key.t and /host/pgpg/tests/t34-split-key.t differ
Only in /host/pgpg/tests/: test-results
Only in /host/pgpg/tests/: trash directory.t00-trivial
Only in /host/pgpg/tests/: trash directory.t28-key-gen-withpass
Only in /host/pgpg/tests/: trash directory.t29-key-revcert
```

> About haveged, the key message may be this: 'Failed to configure loopback device: Operation not permitted'. You can google for it.

Ok, I am looking into this.

>Why it works for me but not for you? I am running docker as root, maybe you are not. Maybe you have a different version of docker. Maybe you have a different version of systemd, a different version of kernel, etc. Maybe you are running AppArmor and it affects the work of docker. I don't know.

I run the ds commands with `sudo` and it is working fine on other cases I also tried adding myself to the docker group but it still is the same. 

>First of all make sure that you don't have problems with the disk space, and also try a reboot (sometimes it solves the problem for me, since I keep it sleep-and-wake for months).

No both of these issues are not there, I do shut down my pc once in a day and it has more than 4 GB of space on my UBUNTU partition even after installing all containers.

**Comment by dashohoxha** [comment]
> `==> # diff -qr /host/egpg/tests /host/pgpg/tests/`

I have used `diff -ru`, but it does not matter. It seems clear that my `pgpg` is not the same as your `pgpg`. Try to remove `.gitignore` files and then do `git status` and then add the needed files.

**Comment by diveshuttam** [comment]
Ah! I didn't look into this. Thanks its working now I tried cloning it fresh and running the tests also.
I have been using a script that copies my current working directory to `/var/ds/pgpg-bionic` so I didn't get this problem. Though I have added these I haven't changed .gitignore as IMO pubrings should not be published until intended.

**Review by sourabhtk37 — APPROVED** [review]
LGTM

**Pull request merged**
