### PR TITLE
add contact trust

### LINKED ISSUE #43: Update contact/trust.sh
https://github.com/EasyGnuPG/pgpg/blob/d108baf68dc2eb6de3d360b4bb1e06f2017d0946/src/cmd/contact/trust.sh#L38-L40

### PR DESCRIPTION
**Pull request by diveshuttam**
closes #43 

reference:
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=lang/python/examples/inter-edit.py;hb=66c2a99422dd9a52d8342165ed1d033c4f29b9e0

### CODE REVIEW

**Comment by dashohoxha** [comment]
Is there no way to do it without interaction? A better way would be to call a function that sets the trust level of a contact to the given value. Or it can work like this: you first load all the details of a contact as an object, you modify some settings on this object, then you save the object (or the changes are saved automatically as soon as you make them).

The disadvantages of interaction are that it is low level, counter-intuitive to programming, and it is not much different from what we are already doing with the `gpg` command. If we still have to do things the same way, there is not much benefit from replacing the `gpg` command with `gpgme` function calls. Instead, we are just replacing 2 lines of code by 50 lines of code, increasing the complexity and making it more difficult to maintain. This questions the usefulness of these replacements that we are doing.

Divesh, I am not blaming you for this, I am just discussing. Even if what we are doing turns out to be not so useful, at least it has helped you (and me) to understand better how GPG works.

**Review by dashohoxha — APPROVED** [review]
I guess there is no other way (other than interactive). So let's get moving. We can discuss later about how useful is to replace `gpg` commmands by `gpgme` function calls.

**Comment by diveshuttam** [comment]
>Divesh, I am not blaming you for this, I am just discussing. Even if what we are doing turns out to be not so useful, at least it has helped you (and me) to understand better how GPG works.

Yes I understand this and I am fine with discussion and correcting my mistakes. I didn't feel that you are blaming at any point.  

> I guess there is no other way (other than interactive). So let's get moving. We can discuss later about how useful is to replace gpg commands by gpgme function calls.

I did it from the documentation and examples but couldn't find another way as of now. Since only a few commands are left, we may have a look again at this after I finish them. Mostly it will be done by the coming week.

**Comment by dashohoxha** [comment]
> Since only a few commands are left, we may have a look again at this after I finish them. Mostly it will be done by the coming week.

OK, after you finish them, I will start a discussion on gnupg-devel about how useful is this, explaining also my reasons and my concerns.

**Pull request merged**
