### PR TITLE
[WIP] Create a basic pip setup and install instructions

### LINKED ISSUE #2: Creating basic pip setup for the project
Create basic pip based setup 
Also documenting how to setup development environment for testing so that others could track current progress

### PR DESCRIPTION
**Pull request by diveshuttam**
Closes #2 
Refered [python guide for packaging](https://python-packaging-user-guide.readthedocs.io/guides/distributing-packages-using-setuptools/) and created a basic pip setup as well as README.md

TODO:
Need to decide on module structure and functions. Currently planned is:
```
/setup.py		# setup file for python
/README.md
/pgpg
-----/cli.py		# contains the main commands for interface
-----/contacts/		# package for managing contacts
-----/keys/		# package for key management
-----/core/		# main package for sign, verify, open, seal etc
-----/utils/		# some other utility scripts helpful in the project may be used for extension in future
/docs
-----/man/		# will contain the man pages for egpg
-----/apidocs/		# will contain the documentation of the library calls and EGPG 
-----/html/		# html documentation for the project that can be hosted on GitHub pages
/tests 			# unit test for egpg will be in this folder.
/LICENCE.txt
```
@sourabhtk37 on reading a few articles on structuring code I think doing this just the module and functions way would be better. I don't think we need much of object orientation here (the only objects I can think are the keys).[ [REFERENCE](http://docs.python-guide.org/en/latest/writing/structure/#object-oriented-programming) ]
Need your suggestions on this as well as the structure.

Also I think it would be good if we can install some lint checker on this repo which checks for PEP-8. Please suggest if you have some in mind.

### CODE REVIEW

**Comment by dashohoxha** [comment]
On your last week's report, I think that you found out that pip is not recommended for distributing GPGME python apps, so you decided to distribute it only by a deb package. Unless I am missing something.

Anyway, it does not seem suitable to me to think about distributing the application before finishing it, or before even developing some parts of it. So, I would postpone this issue for the end.

I agree that you don't need to use OO programming. This is a simple program, and it is better to keep the code simple as much as possible. An easy way to get started, in my opinion, would be to create a structure similar to that of the existing (bash) application, with the same functions, similar directory and file structure, etc. Later you can refactor it, if needed, to make it better.

The same goes for the coding style and standards (PEP-8 etc.) You don't have to worry to much right now, because you can improve it later, if needed. For the time being just use any codding style that seems reasonable, and try to be consistent as much as possible.

So, the principle that we are using here is: First make it work, then make it better.

**Comment by diveshuttam** [comment]
@dashohoxha Yes the bindings won't be a part of `pip package` itself they would have to be installed separately

Also this setup helps as:
- Since this is also a library and can be imported it is needed to be made available as a pip package so that one can easily import this in any python module once it is installed. 
- I read in some Debian guide that we can easily integrate pip packages into deb (I can't remember the source now, will add as I find it) so developing this as a pip package will probably make final packaging much easier. 
-  This makes the installation/uninstall process during testing easier. Python is opinited about is installation, generally people don't write Makefiles for python packages and applications. Also `pip` has support for a develop mode for installation in which I can experiment and code simultaneously. Python will manage this scripts installation and making it available as an executable for testing as well as a library. (see readme for install process) 
- We can easily integrate various test frameworks into `pip` installations . Though currently they are not needed we can use the egpg tests only but may be at later stage it can be helpful in writing python specific tests.

Lastly this package won't be published on to PYPI, will probably be a direct part of the Debian package. At the very least this can be helpful in the development stage I won't have to write Makefile for managing installation etc. 
If not required finally we may remove this there isn't much code in here.

**Comment by dashohoxha** [comment]
Since I don't have much experience with Python myself, I trust your decisions and what @sourabhtk37 may suggest.

I would also like to invite @YagoGG to give any opinion or suggestion on this, if possible.

**Comment by diveshuttam** [comment]
I added all the reasons I can think of. Though most of this can be done using some other (maybe better) ways later. I think this will work out better if we have a pip package from the start. I would like you to trust me on this for now. I will remove this setup if required before final packaging. It majorly helps with easy installation and workflow for now.

**Comment by dashohoxha** [comment]
@diveshuttam I do trust you. I just wanted to get some feedback or suggestions for the questions that you asked in the beginning: https://github.com/EasyGnuPG/pgpg/pull/18

**Review by dashohoxha — APPROVED** [review]
@diveshuttam you can merge it if you are already done.

**Comment by diveshuttam** [comment]
@sourabhtk37, Thanks I will have a look at the code once and think about the key class.
Regarding documentation, I had thought of using sphinx at a later stage may be after the second evaluation. Till then I'll add the basic documentation in markdown and later generate the final GitHub pages for usage of the CLI as well as the library calls using sphinx.

**Pull request merged**
